package com.xworkz.javacollection.constant;

public enum WeaponType {
	KNIVES_BAYONETS, SMALL_ARMS, NONLINEAR_LINE_OF_SIGHT_WEAPONS, SHOTGUNS, SMG, ASSAULT_RIFLES, SNIPER_RIFLES,
	ANTI_MATERIAL_REFLIES, MACHINE_GUNSEXPLOSIVES,MINES;

}
